S3Uploader 리팩토링
Instagram-Clone-Coding/Spring_instagram-clone pull request #194
Opened 2022-08-09 10:22 UTC by bluetifulc

## 📌Linked Issues
- Resolve: #191 

## ✏Change Details
### 멤버 DTO, 엔티티 관련 리팩토링
- 기존엔 멤버에서 여러 데이터를 뽑거나 수정하는 경우 하나하나 getter, setter를 통해 변경
- 다중 getter -> DTO 생성자에서 파라미터로 Entity를 받도록 수정
- 다중 setter -> 하나의 update메서드를 만들어 수정하도록 개선
### S3Uploader 리팩토링
- CantConvertFileException 예외명 수정 -> FileConvertFailException
- S3Uploader의 내부 로직 리팩토링
  - 메서드 명을 자세하게 수정
  - 메서드 내부 로직 관련
    - filename을 만드는 등 중복되는 작업을 메서드로 추출
    - 뒤엉켜있던 메서드의 역할을 분리(특히 upload 관련 메서드의 경우) -> 좀 더 일반적인 메서드(upload, putS3)와 구체적인 메서드(uploadImage)로 역할을 구분
  - deleteImage 메서드의 시그니처를 uploadImage와 동일한 순서로 변경
  - 내부 로직에서 비효율적인 Exception처리 과정 개선
### 기타 수정
- `ResultCode`, `ErrorCode`의 `status` 변수를 `final`로 지정

## 💬Comment
- Member 도메인 리팩토링, 테스트 작성하다가 S3Uploader 코드 상태를 보고 먼저 리팩토링해야겠다고 생각했습니다. 그래서 커밋에 Member관련 커밋이 하나 껴있습니다..
- 해당 PR 머지 후 다시 Member도메인 테스트작성+리팩토링 진행하겠습니다.
- #193 이슈로 아직 포스트 이미지 관련 테스트는 진행하지 못하였습니다. (멤버 프로필 사진 테스트만 완료)

## 📑References
- 

## ✅Check List
- [x] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [x] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?

2022-08-09 14:33 UTC, seonpilKim requested changes

2022-08-09 14:33 UTC, seonpilKim commented on src/main/java/cloneproject/Instagram/domain/member/entity/Member.java
> +		this.gender = Gender.valueOf(editProfileRequest.getMemberGender());
Entity가 Dto를 의존하는 것은 Anti-pattern으로 알고 있습니다.
고수준 내부 모듈(entity)이 저수준 외부 모듈(request dto)에 의존하는 형태가 되므로, 좋지 않은 설계라고 생각합니다.

물론 프로필을 수정하는 attributes이 모두 entity의 attributes이기 때문에, 클라이언트의 요청 데이터 규격이 바뀌면 entity도 수정이 불가피하긴 하지만,
외부에서 들어오는 요청 데이터 규격이 바뀌었다고, entity도 건드려야 하는 건 마치 갑과 을이 바뀐 상황이 아닐까요?

오히려 기존의 방식처럼 각 attribute마다 변경하는 메소드를 일일이 호출하는 방식이 위와 같은 측면에서는 더 낫지 않을까 하는 생각이 듭니다만, 비즈니스 로직에 너무 긴 코드가 담기는 것 같다는 생각도 드는 것 같아요. 의미있는 하나의 단위로 압축하고 싶은 생각이 드네요. 이건 다훈님도 똑같이 생각하셨을 것 같아요.

그래서 다른 두 가지 방법을 제안드립니다.

1. **Service layer에 private method를 만들어서 사용하기**
```java
	private void editProfile(EditProfileRequest request, Member member) {
		member.updateUsername(request.getMemberUsername());
    		...
    		member.updateGender(request.getMemberGender());
	}
// -------------------------------------------------------------------------------------------
        // 수정 후
	public void editProfile(EditProfileRequest editProfileRequest) {
		final Member member = authUtil.getLoginMember();

		if (memberRepository.existsByUsername(editProfileRequest.getMemberUsername())
			&& !member.getUsername().equals(editProfileRequest.getMemberUsername())) {
			throw new UsernameAlreadyExistException();
		}

		editProfile(editProfileRequest, member);
	}
```
2. **Profile VO로 묶고, VO 내부에 비즈니스 메소드를 생성해서 사용하기**
```java
@Getter
@Builder
@Embeddable
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Profile { // Member.java도 수정 必

	private String username;
	...
	private Gender gender;

	@Override
	public int hashCode() {
		...
	}

	@Override
	public boolean equals(Object obj) {
		...
	}

        public void update(EditProfileRequest request) {
		this.username = request.getMemberUsername();
		...
		this.gender = Gender.valueOf(request.getMemberGender());        
        }

}
// -------------------------------------------------------------------------------------------
        // 수정 후
	public void editProfile(EditProfileRequest editProfileRequest) {
		final Member member = authUtil.getLoginMember();

		if (memberRepository.existsByUsername(editProfileRequest.getMemberUsername())
			&& !member.getUsername().equals(editProfileRequest.getMemberUsername())) {
			throw new UsernameAlreadyExistException();
		}

		member.getProfile().update(editProfileRequest);
	}
```

참고로 마지막에 `memberRepository.save(member);`는 제거하셔도 됩니다.
jpa가 commit 시점에 영속성 컨텍스트를 확인해서 dirty checking을 통해 자동으로 업데이트 쿼리를 실행시켜줍니다.
대신 메소드에 `@Transactional`을 추가해 주세요.

회의 때 한 번 간단히 언급드린 내용이지만, 기존에는 SimpleJpaRepository.save() 메소드에 기본적으로 `@Transactional`이 붙어있어서 해당 쿼리가 실행된 거라고 이해하시면 될 것 같습니다.

2022-08-09 14:33 UTC, seonpilKim commented on src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
> +}
![](https://user-images.githubusercontent.com/68049320/183082664-86cd47ae-f08f-40da-a22d-76829042dfa3.png)

위와 같이 설정하시면 코드 정렬할 때 같이 적용돼서 편하게 컨벤션에 맞게 개발하실 수 있을 거에요 :)

2022-08-09 14:33 UTC, seonpilKim commented on src/main/java/cloneproject/Instagram/global/result/ResultCode.java
> +	private final int status;
👍

2022-08-10 02:33 UTC, bluetifulc commented on src/main/java/cloneproject/Instagram/domain/member/entity/Member.java
> +		this.gender = Gender.valueOf(editProfileRequest.getMemberGender());
안그래도 뭔가 마음에 안들어서 고민하고 있었는데 좋은 방법이네요.
2번째 방법이 더 마음에 드는데 member와 연관있는 객체가 많아서 수정하기 까다로울 것 같네요.

2022-08-11 12:49 UTC, seonpilKim commented on src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
> +}
해당 파일 재확인 부탁드립니다~!

2022-08-11 12:49 UTC, seonpilKim approved these changes

2022-08-11 13:50 UTC, merged

2022-08-13 12:47 UTC, bluetifulc commented on src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
> +}
커멘트를 지금 확인했는데 어느 부분에 문제가 있나요 ?

2022-08-13 13:01 UTC, seonpilKim commented on src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
> +}
6번째 라인이 비어있지 않네요

2022-08-13 13:12 UTC, bluetifulc commented on src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
> +}
저는 비어있는 걸로 보이는데 다시 확인해주실 수 있나요 ??

2022-08-13 13:18 UTC, seonpilKim commented on src/main/java/cloneproject/Instagram/global/error/exception/FileConvertFailException.java
> +}
어 그러네요.,.? 뭐지 방금까지도 붙어있게 보였는데 ;;.. 캐싱때문인가